export const icons=['hotel','lake','grass','spring','waterfall','village','cafe','restaurant','airport','market','coast','pagoda-gold','pagoda-silver','garden'];
function fail(path,msg){throw Error(path+': '+msg);}
function text(v,p,max=2000,empty=false){if(typeof v!=='string'||v.length>max||(!empty&&!v.trim()))fail(p,'需要有效文本');}
function id(v,p){text(v,p,60);if(!/^[a-z][a-z0-9-]*$/.test(v)||['constructor','prototype','__proto__'].includes(v))fail(p,'编号需为小写字母、数字和连字符');}
function arr(v,p,min=0,max=100){if(!Array.isArray(v)||v.length<min||v.length>max)fail(p,`需要 ${min}—${max} 项`);}
export function date(v,p){if(typeof v!=='string'||!/^20\d\d-\d\d-\d\d$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail(p,'日期需为有效 YYYY-MM-DD');}
function url(v,p){text(v,p,2000,true);if(v==='')return;let u;try{u=new URL(v);}catch{fail(p,'网址无效');}if(!['http:','https:'].includes(u.protocol)||u.username||u.password)fail(p,'只接受不含凭据的 HTTP(S) 网址');}
function fields(o,required,optional,p){if(!o||typeof o!=='object'||Array.isArray(o))fail(p,'需要对象');for(const k of required)if(!Object.hasOwn(o,k))fail(p,'缺少 '+k);for(const k of Object.keys(o))if(![...required,...optional].includes(k))fail(p,'不支持字段 '+k);}
const unique=(list,p)=>{if(new Set(list).size!==list.length)fail(p,'编号/名称重复');};
export function validateTrip(t){
 fields(t,['schemaVersion','id','title','headline','subtitle','startDate','endDate','travelers','currency','cities','meta','places','days','foods','hotels','regions','practical'],[],'trip');
 if(t.schemaVersion!==1)fail('schemaVersion','只支持 1');id(t.id,'id');for(const k of ['title','headline','subtitle'])text(t[k],k,k==='title'?40:200);
 date(t.startDate,'startDate');date(t.endDate,'endDate');const count=(Date.parse(t.endDate)-Date.parse(t.startDate))/86400000+1;if(count<1||count>31)fail('dates','支持1—31天，结束日期不得早于开始');
 if(!Number.isInteger(t.travelers)||t.travelers<1||t.travelers>99)fail('travelers','需要1—99人数');if(t.currency!=='CNY')fail('currency','此版账本仅支持人民币；不自动换汇');
 arr(t.cities,'cities',1,12);t.cities.forEach(x=>text(x,'city',30));unique(t.cities,'cities');if(t.cities.some(x=>['全部','跨城 / 其他'].includes(x)))fail('cities','名称与筛选保留项冲突');
 arr(t.meta,'meta',0,4);t.meta.forEach(x=>text(x,'meta',100));arr(t.places,'places',1,120);unique(t.places.map(p=>p.id),'places');
 for(const p of t.places){fields(p,['id','name','city','type','icon','desc','stay','caption','status','mapUrl','sourceUrl','checkedAt','verification','locationNote'],[],'place');id(p.id,'place.id');for(const k of ['name','city','desc','stay','caption','status','locationNote'])text(p[k],'place.'+k,k==='name'?24:2000);if(!t.cities.includes(p.city))fail(p.id,'城市未定义');if(!['景点','餐饮','咖啡','酒店','交通'].includes(p.type)||!icons.includes(p.icon))fail(p.id,'类别或图形不支持');url(p.mapUrl,p.id+'.mapUrl');url(p.sourceUrl,p.id+'.sourceUrl');if(p.checkedAt!=='')date(p.checkedAt,p.id+'.checkedAt');if(!['verified','lead','unknown'].includes(p.verification))fail(p.id,'核实状态无效');if(p.verification==='verified'&&(!p.sourceUrl||!p.checkedAt))fail(p.id,'已核实必须有来源与核实日期');}
 const placeIds=new Set(t.places.map(p=>p.id));const ref=(v,p)=>{if(!placeIds.has(v))fail(p,'引用未知地点 '+v);};
 arr(t.days,'days',count,count);unique(t.days.map(d=>d.id),'days');const itemIds=[];
 for(const [index,d] of t.days.entries()){fields(d,['id','date','city','title','intro','warn','region','items'],[],'day');id(d.id,'day.id');date(d.date,'day.date');if(Date.parse(d.date)!==Date.parse(t.startDate)+index*86400000)fail(d.id,'日期必须连续并覆盖整趟行程');for(const k of ['city','title','intro','warn'])text(d[k],'day.'+k);if(!t.cities.includes(d.city))fail(d.id,'城市未定义');arr(d.items,d.id+'.items',1,12);
  for(const i of d.items){fields(i,['id','time','name','desc','tag','placeId'],[],'item');id(i.id,'item.id');itemIds.push(i.id);for(const k of ['time','name','desc','tag'])text(i[k],'item.'+k,2000,k==='tag');if(i.placeId!==null)ref(i.placeId,i.id);}}
 unique(itemIds,'items');
 arr(t.foods,'foods',0,100);unique(t.foods.map(f=>f.placeId),'foods');for(const f of t.foods){fields(f,['placeId','type','kind'],[],'food');ref(f.placeId,'food');if(!['早餐','正餐','小吃','咖啡'].includes(f.type))fail('food.type','无效');text(f.kind,'food.kind');}
 arr(t.hotels,'hotels',0,30);unique(t.hotels.map(h=>h.placeId),'hotels');for(const h of t.hotels){fields(h,['placeId','checkIn','checkOut','risk'],[],'hotel');ref(h.placeId,'hotel');if(t.places.find(p=>p.id===h.placeId).type!=='酒店')fail('hotel','必须引用酒店类型');date(h.checkIn,'checkIn');date(h.checkOut,'checkOut');if(h.checkIn<t.startDate||h.checkOut>t.endDate||h.checkOut<=h.checkIn)fail('hotel','入住退房日期需位于行程内，退房晚于入住');text(h.risk,'hotel.risk');}
 arr(t.regions,'regions',1,30);unique(t.regions.map(r=>r.id),'regions');const coverage=new Set();
 for(const r of t.regions){fields(r,['id','name','title','en','note','nodes','routes'],['panels','areas','unlocated','terrain'],'region');id(r.id,'region.id');for(const k of ['name','title','en','note'])text(r[k],'region.'+k);arr(r.nodes,'nodes',r.panels?0:1,40);if(r.nodes.filter(n=>!n.detail).length>12)fail('nodes','大模型最多12个，其余节点使用detail或拆分片区');unique(r.nodes.map(n=>n.placeId),'nodes');
  for(const n of r.nodes){fields(n,['placeId','x','y'],['detail'],'node');if(n.detail!==undefined&&typeof n.detail!=='boolean')fail('node.detail','需要布尔值');ref(n.placeId,'node');coverage.add(n.placeId);if(!Number.isFinite(n.x)||n.x<110||n.x>890||!Number.isFinite(n.y)||n.y<110||n.y>560)fail('node','坐标需在x110—890/y110—560内');}
  if(r.terrain!==undefined&&!['hills','lowland'].includes(r.terrain))fail('terrain','地形无效');
  if(r.unlocated){arr(r.unlocated,'unlocated',0,30);unique(r.unlocated,'unlocated');for(const id of r.unlocated){ref(id,'unlocated');if(r.nodes.some(n=>n.placeId===id))fail('unlocated','不能同时标点和待定位');coverage.add(id);}}
  if(r.areas){arr(r.areas,'areas',0,12);for(const a of r.areas){fields(a,['label','x','y','w','h'],[],'area');text(a.label,'area.label',80);for(const k of ['x','y','w','h'])if(!Number.isFinite(a[k])||a[k]<0)fail('area','无效坐标');if(a.x+a.w>1000||a.y+a.h>670)fail('area','区域超出画布');}}
  if(r.panels){arr(r.panels,'panels',1,12);unique(r.panels,'panels');for(const id of r.panels){const child=t.regions.find(p=>p.id===id);if(!child||child===r||child.panels)fail('panels','总览只能引用已有城市图');}const all=new Set(r.panels.flatMap(id=>{const p=t.regions.find(p=>p.id===id);return [...p.nodes.map(n=>n.placeId),...(p.unlocated||[])];}));for(const n of r.nodes)if(!all.has(n.placeId))fail('panels','总览地点必须来自城市图');}
  arr(r.routes,'routes',0,31);unique(r.routes.map(q=>q.dayId),'routes');const onMap=new Set(r.panels?r.panels.flatMap(id=>{const p=t.regions.find(p=>p.id===id);return [...p.nodes.map(n=>n.placeId),...(p.unlocated||[])];}):r.nodes.map(n=>n.placeId));
  for(const q of r.routes){fields(q,['dayId','stops','legs'],[],'route');if(!t.days.some(d=>d.id===q.dayId))fail('route','日期未定义');arr(q.stops,'stops',1,30);arr(q.legs,'legs',r.panels?0:q.stops.length-1,r.panels?0:q.stops.length-1);for(const s of q.stops)if(!onMap.has(s))fail('route','路线地点不在此图中');
   for(const [i,l]of q.legs.entries()){fields(l,['from','to','path','label','x','y','optional','returning'],[],'leg');if(l.from!==q.stops[i]||l.to!==q.stops[i+1]||l.from===l.to)fail('leg','连线必须逐段对应停留顺序');text(l.path,'path',300);if(!/^M[-\d.,\s]+Q[-\d.,\s]+$/.test(l.path))fail('leg.path','使用单段 M … Q … 曲线');const nums=l.path.match(/-?\d+(?:\.\d+)?/g);if(nums?.length!==6||nums.some(n=>!Number.isFinite(+n)||+n<0||+n>1000))fail('leg.path','需要6个画布内坐标');text(l.label,'leg.label',40);if(!Number.isFinite(l.x)||l.x<0||l.x>1000||!Number.isFinite(l.y)||l.y<0||l.y>670||typeof l.optional!=='boolean'||typeof l.returning!=='boolean')fail('leg','标注位置或状态无效');}}
 }
 for(const p of t.places)if(!coverage.has(p.id))fail('regions','地点未进入任何沙盘 '+p.id);
 for(const d of t.days){const r=t.regions.find(r=>r.id===d.region);if(!r)fail(d.id,'默认区域不存在');if(!r.routes.some(q=>q.dayId===d.id))fail(d.id,'默认区域缺少当天路线');}
 arr(t.practical,'practical',0,20);unique(t.practical.map(p=>p.id),'practical');for(const p of t.practical){fields(p,['id','title','summary','detail'],[],'practical');id(p.id,'practical.id');for(const k of ['title','summary','detail'])text(p[k],'practical.'+k);}
 return t;
}
